#!/usr/bin/env bash
set -ex

# This is the master script for the capsule. When you click "Reproducible Run", the code in this file will execute.
# python -u run_capsule.py "$@"
# python -u run_capsule-test.py "$@"
# python -u run_capsule-test_baseline_rl.py "$@"
# python -u run_capsule-test-detailed_ana_on_generative_runs.py "$@"
python -u run_capsule-test_likelihood_comparison.py "$@"

# if loading_mice_data
# python -u load_mice_data.py --all-subjects "$@"
# python -u load_mice_data.py --subject-ids 778149 778147 753618 "$@"
# # Load first 3 subjects (default)
# python load_mice_data.py
# # Load with stage filtering
# python load_mice_data.py --num-subjects 10 --stages STAGE_FINAL GRADUATED